### ISSUE TITLE
Transition hybrid communication to use internal JWT tokens

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-envoy#7]
# Summary
Transition Apigee Adapter for Envoy’s internal communications with Apigee to a more secure authentication and authorization model by using a rotating JWT token. 

Note: Only hybrid will adopt internal JWT tokens, but ALL platforms will transition to exclusively use CRD-style configuration. Plain yaml configuration files will not longer be supported. This is potentially a breaking change.

# CLI provision
- Eliminate creation of API Product and App
- Load existing config file w/ secrets (see config file section below)
- Generate a new private key and JWKs if no existing config or if requested.
- A `--rotate` option will be added to create a new privateKey and emit new JWKs.

# CLI create-secret
- Remove in favor of provision handling capabilities.

# Client
- Once private configuration is loaded, retrieve key ID and private key
- Create and rotate short-term JWTs to use for communication
- Exit immediately if JWT token cannot be created

# Proxy
- Replace API Key validation with JWT using existing JWKs
- Use a different audience so it’s not interchangeable with client JWTs

# Config file
- Standardize on the Kubernetes CRD as the format both inside and outside of Kubernetes. 
- The file will only include the ConfigMap for SaaS and OPDK.
- The file will always include both the ConfigMap and Secret CRDs for Hybrid.
- Eliminate tenant/key and tenant/secret from config for Hybrid.

# Inside Kubernetes
Kubernetes will mount the ConfigMap and Secret as separate volumes. So, a new optional parameter will be added to the binary: `--policy-secret=/path`. The default path will be `/policy-secret`. 

If the Secret CRD isn’t found in the --config file, the adapter will look in this location for the Secret files:
```
/policy-secret/remote-service.crt
/policy-secret/remote-service.key
/policy-secret/remote-service.properties
```
(This will work the same outside of Kubernetes.)

Finally, we will add a volume and volume mount for the sample Deployment to mount the standard Apigee secret:
```
        volumeMounts:
        - mountPath: /policy-secret
          name: policy-secret
          readOnly: true
        volumes:
        - name: policy-secret
          secret:
            defaultMode: 420
            secretName: org-env-policy-secret
```

(The `secretName: org-env-policy-secret` will need to be edited by the user to match their org & env.)
